# version: "3.9"
# services:
#   db:
#     image: postgres:15
#     restart: always
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: fastapi-local-db
#     ports:
#       - "5432:5432"
#     volumes:
#       - pgdata:/var/lib/postgresql/data

#   api:
#     build: .
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
#     env_file:
#       - .env
#     volumes:
#       - .:/app
#     command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

# volumes:
#   pgdata:

version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fastapi-local-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload
      --reload-dir app
      --reload-exclude .venv
      --reload-exclude alembic
      --reload-exclude __pycache__
      --reload-exclude migrations
      --reload-exclude logs

volumes:
  pgdata:
